---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      version: 0.10.7
  install:
    createNamespace: true
  interval: 10m0s
  targetNamespace: external-secrets
