---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: crossplane
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/mproffitt/crossplane-apis
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-configurations
  namespace: default
spec:
  dependsOn:
    - name: crossplane
      namespace: flux-system
  interval: 10m0s
  path: ./cluster/apps/configurations
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-claims
  namespace: default
spec:
  dependsOn:
    - name: crossplane-configurations
      namespace: default
  interval: 10m0s
  path: ./cluster/apps/claims
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane
    namespace: flux-system
