apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: xrepository
  labels:
    pkg.crossplane.io/owner: mproffitt
    pkg.crossplane.io/version: 0.0.1-e249c47
spec:
  crossplane:
    version: ">=v1.17.0"
  dependsOn:
    - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
      version: ">=0.3.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-kcl
      version: ">=0.10.10"
