apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  creationTimestamp: null
  labels:
    owner: mproffitt
    provider: github
  name: github-pull-request
spec:
  compositeTypeRef:
    apiVersion: xrepository.crossplane.choclab.net/v1alpha1
    kind: PullRequest
  mode: Pipeline
  pipeline:
    - functionRef:
        name: crossplane-contrib-function-kcl
      input:
        apiVersion: krm.kcl.dev/v1alpha1
        kind: KCLInput
        metadata:
          creationTimestamp: null
        spec:
          config: {}
          credentials:
            password: ""
            username: ""
          source: oci://ghcr.io/mproffitt/kcl-test:0.0.1-c267d7c
          target: ""
      step: step-kcl-do-something
    - functionRef:
        name: crossplane-contrib-function-auto-ready
      step: function-auto-ready
